CC := g++  
RM := rm -f  
LIBS =  
  
all:	RemoveDuplicatesFromSortedArray SearchInRotatedSortedArray	MedianOfTwoSortedArrays ClimbingStairs

RemoveDuplicatesFromSortedArray:	RemoveDuplicatesFromSortedArray.cpp
	$(CC)	RemoveDuplicatesFromSortedArray.cpp -o	../debug/RemoveDuplicatesFromSortedArray
	
SearchInRotatedSortedArray:	SearchInRotatedSortedArray.cpp
	$(CC)	SearchInRotatedSortedArray.cpp -o	../debug/SearchInRotatedSortedArray
	
MedianOfTwoSortedArrays:	MedianOfTwoSortedArrays.cpp
	$(CC)	MedianOfTwoSortedArrays.cpp -o	../debug/MedianOfTwoSortedArrays
	
ClimbingStairs:	ClimbingStairs.cpp
	$(CC)	ClimbingStairs.cpp -o	../debug/ClimbingStairs
	
ReverseLinkedList:	ReverseLinkedList.cpp
	$(CC)	ReverseLinkedList.cpp -o	../debug/ReverseLinkedList
	
	
Test:	Test.cpp
	$(CC)	Test.cpp -o	../debug/Test
	
	